name: Update aqua-checksums.json

on:
  pull_request:
    branches: [main]

permissions:
  contents: write # required to push a commit to update aqua-checksums.json

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  aqua-update-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v1.28.0
      - uses: aquaproj/update-checksum-action@feat/support-prune
        with:
          prune: true
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
