name: Update aqua-checksums.json

on:
  pull_request:
    branches: [main]
    paths:
      - aqua.yaml
      - aqua-checksums.json
      - .github/workflows/aqua-update-checksum.yaml

permissions:
  contents: write # required to push a commit to update aqua-checksums.json

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  aqua-update-checksum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v1.25.0
      - uses: aquaproj/update-checksum-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
